# Désactiver Nixpacks et utiliser le Dockerfile existant
[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NIXPACKS_DISABLE = "true"
NIXPACKS_NODE_PACKAGE_MANAGER = "npm"
NODE_VERSION = "22" 